-- AstroCommunity: import any community modules here
-- We import this file in `lazy_setup.lua` before the `plugins/` folder.
-- This guarantees that the specs are processed before any user plugins.
---@type LazySpec
return {
    "AstroNvim/astrocommunity",
    {import = "astrocommunity.bars-and-lines.dropbar-nvim"},
    {import = "astrocommunity.bars-and-lines.statuscol-nvim"},
    -- { import = "astrocommunity.code-runner.toggletasks-nvim" },
    -- { import = "astrocommunity.code-runner.compiler-nvim" },
    {import = "astrocommunity.code-runner.overseer-nvim"},
    {import = "astrocommunity.color.tint-nvim"},
    -- {import = "astrocommunity.color.twilight-nvim"},
    {import = "astrocommunity.comment.ts-comments-nvim"},
    {import = "astrocommunity.completion.blink-cmp-emoji"},
    {import = "astrocommunity.completion.blink-cmp-git"},
    -- { import = "astrocommunity.completion.tabby-nvim" },
    {import = "astrocommunity.debugging.persistent-breakpoints-nvim"},
    -- { import = "astrocommunity.diagnostics.error-lens-nvim" },
    {import = "astrocommunity.diagnostics.lsp_lines-nvim"},
    -- { import = "astrocommunity.diagnostics.tiny-inline-diagnostic-nvim" },
    {import = "astrocommunity.diagnostics.trouble-nvim"},
    {import = "astrocommunity.editing-support.mini-splitjoin"},
    {import = "astrocommunity.editing-support.neogen"},
    {import = "astrocommunity.editing-support.nvim-origami"},
    -- { import = "astrocommunity.editing-support.quick-scope" },
    {import = "astrocommunity.editing-support.refactoring-nvim"},
    {import = "astrocommunity.editing-support.rustowl"},
    {import = "astrocommunity.editing-support.telescope-undo-nvim"},
    -- { import = "astrocommunity.editing-support.vim-move" },
    {import = "astrocommunity.editing-support.yanky-nvim"},
    {import = "astrocommunity.editing-support.zen-mode-nvim"},
    {import = "astrocommunity.fuzzy-finder.telescope-nvim"},
    {import = "astrocommunity.git.diffview-nvim"},
    {import = "astrocommunity.git.git-blame-nvim"},
    {import = "astrocommunity.git.mini-diff"},
    {import = "astrocommunity.markdown-and-latex.markdown-preview-nvim"},
    {import = "astrocommunity.markdown-and-latex.markmap-nvim"},
    {import = "astrocommunity.markdown-and-latex.markview-nvim"},
    {import = "astrocommunity.markdown-and-latex.peek-nvim"},
    {import = "astrocommunity.markdown-and-latex.texpresso-vim"},
    {import = "astrocommunity.media.image-nvim"},
    {import = "astrocommunity.media.img-clip-nvim"},
    {import = "astrocommunity.media.vim-wakatime"},
    {import = "astrocommunity.motion.flash-nvim"},
    {import = "astrocommunity.neovim-lua-development.helpview-nvim"},
    {import = "astrocommunity.note-taking.global-note-nvim"},
    -- { import = "astrocommunity.note-taking.neorg" },
    {import = "astrocommunity.note-taking.venn-nvim"},
    {import = "astrocommunity.pack.bash"}, {import = "astrocommunity.pack.lua"},
    {import = "astrocommunity.pack.cpp"}, {import = "astrocommunity.pack.fish"},
    {import = "astrocommunity.pack.json"},
    {import = "astrocommunity.pack.markdown"},
    {import = "astrocommunity.pack.mdx"}, {import = "astrocommunity.pack.pkl"},
    {import = "astrocommunity.pack.python-ruff"},
    {import = "astrocommunity.pack.rust"},
    {import = "astrocommunity.pack.toml"},
    {import = "astrocommunity.pack.yaml"},
    -- {import = "astrocommunity.project.project-nvim"},
    {import = "astrocommunity.quickfix.quicker-nvim"},
    {import = "astrocommunity.scrolling.satellite-nvim"},
    {import = "astrocommunity.scrolling.neoscroll-nvim"},
    {import = "astrocommunity.search.grug-far-nvim"},
    -- {import = "astrocommunity.split-and-window.colorful-winsep-nvim"},
    {import = "astrocommunity.split-and-window.edgy-nvim"},
    {import = "astrocommunity.split-and-window.windows-nvim"},
    {import = "astrocommunity.utility.telescope-fzy-native-nvim"},
    {import = "astrocommunity.utility.telescope-lazy-nvim"},
    {import = "astrocommunity.workflow.precognition-nvim"}
    -- import/override with your plugins folder
}
